version: '3.8'

services:

  web:
    build: ./
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8080
    volumes:
      - ./:/usr/src/app
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/foo
      - DATABASE_TEST_URL=postgresql+asyncpg://postgres:postgres@db:5432/test_db
      - TEST_DB_NAME=test_db
      - PATH_IMAGES=/usr/src/app/images/
      - POSTGRES_DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/postgres
      - AWS_ACCESS_KEY_ID=/usr/src/app/cert/AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=/usr/src/app/cert/AWS_SECRET_ACCESS_KEY
      - SECRET_KEY=/usr/src/app/cert/SECRET_KEY
    depends_on:
      - db

  db:
    image: postgres:15.3
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=foo
      - POSTGRES_PORT=2001
      - POSTGRES_HOST=127.0.0.1
    ports:
      - "2001:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U passport-user -d passport"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
