"""drop unique

Revision ID: 22a26844366c
Revises: 92a2a27cfff1
Create Date: 2024-03-19 12:56:46.115279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22a26844366c'
down_revision: Union[str, None] = '92a2a27cfff1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('images_names_name_key', 'images_names', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('images_names_name_key', 'images_names', ['name'])
    # ### end Alembic commands ###
