"""add email send

Revision ID: ac0ecbd3f03e
Revises: 34c58d853aee
Create Date: 2024-02-18 15:55:36.359896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = 'ac0ecbd3f03e'
down_revision: Union[str, None] = '34c58d853aee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emails_send',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlalchemy_utils.types.email.EmailType(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expired_at', sa.DateTime(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emails_send_email'), 'emails_send', ['email'], unique=True)
    op.create_index(op.f('ix_emails_send_id'), 'emails_send', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emails_send_id'), table_name='emails_send')
    op.drop_index(op.f('ix_emails_send_email'), table_name='emails_send')
    op.drop_table('emails_send')
    # ### end Alembic commands ###
