"""add gallery

Revision ID: dee305243055
Revises: 22a26844366c
Create Date: 2024-03-20 15:25:05.107987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dee305243055'
down_revision: Union[str, None] = '22a26844366c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('galleries',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users_images', sa.Column('gallery_id', sa.Text(), nullable=False))
    op.create_foreign_key(None, 'users_images', 'galleries', ['gallery_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_images', type_='foreignkey')
    op.drop_column('users_images', 'gallery_id')
    op.drop_table('galleries')
    # ### end Alembic commands ###
