"""add primary keys

Revision ID: e14e0c278b30
Revises: 0ae1fa7b2dd0
Create Date: 2024-03-16 14:49:04.708714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e14e0c278b30'
down_revision: Union[str, None] = '0ae1fa7b2dd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
